/**
 * Multi-sitemap implementation for SoberNation.
 *
 * Google's sitemap limit is 50,000 URLs per file.
 * With 264k+ pages, we need a sitemap index with multiple child sitemaps.
 *
 * Next.js generateSitemaps() creates:
 *   /sitemap.xml           — sitemap index (auto-generated by Next.js)
 *   /sitemap/0.xml         — static & standalone high-value pages
 *   /sitemap/1.xml         — /help /rehab /alcohol-rehab /drug-rehab (all cities)
 *   /sitemap/2.xml         — alcohol/drug/heroin/cocaine/opiate/cannabis/crack addiction
 *   /sitemap/3.xml         — prescription drugs, ketamine, meth, spice, gambling, etc.
 *   /sitemap/4.xml         — new service routes: detox, counselling, residential, outpatient
 *   /sitemap/5.xml         — support groups: AA, NA, Al-Anon, SMART, CA, 12-step
 *   /sitemap/6.xml         — specialist: dual diagnosis, womens, teen, workplace, family, etc.
 *   /sitemap/7.xml         — milestone & sobriety time pages
 */

import type { MetadataRoute } from 'next'
import { getLocationSlugs } from '../lib/locations'

const BASE = 'https://www.sobernation.co.uk'

// Population-weighted priority (passed to each function)
const HIGH_POP = new Set([
  'london','manchester','birmingham','leeds','glasgow','sheffield','liverpool',
  'bristol','edinburgh','cardiff','leicester','nottingham','coventry','bradford',
  'belfast','stoke-on-trent','wolverhampton','derby','swansea','southampton',
  'portsmouth','norwich','reading','luton','hull','sunderland','exeter',
  'bolton','plymouth','bournemouth','middlesbrough','newcastle-upon-tyne',
  'brighton','oxford','cambridge','york','peterborough','cheltenham',
])
const MED_POP = new Set([
  'bath','chester','worcester','gloucester','ipswich','colchester','guildford',
  'milton-keynes','northampton','stockport','salford','oldham','rochdale',
  'wigan','warrington','wakefield','huddersfield','doncaster','rotherham',
  'barnsley','grimsby','lincoln','shrewsbury','hereford','carlisle','blackpool',
  'burnley','blackburn','dundee','aberdeen','inverness','perth','stirling',
])

function locPriority(slug: string): number {
  if (HIGH_POP.has(slug)) return 0.9
  if (MED_POP.has(slug)) return 0.75
  return 0.55
}

function locationEntries(
  routes: Array<{ route: string; weight: number }>,
  slugs: string[],
  limit = 45000,
): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = []
  const now = new Date()
  for (const { route, weight } of routes) {
    for (const slug of slugs) {
      const priority = Math.round(Math.min(0.95, locPriority(slug) * weight) * 100) / 100
      entries.push({
        url: `${BASE}/${route}/${slug}`,
        lastModified: now,
        changeFrequency: 'monthly',
        priority,
      })
      if (entries.length >= limit) return entries
    }
  }
  return entries
}

export async function generateSitemaps() {
  // 8 sitemap shards
  return [0, 1, 2, 3, 4, 5, 6, 7].map(id => ({ id }))
}

export default async function sitemap({
  id,
}: {
  id: number
}): Promise<MetadataRoute.Sitemap> {
  const slugs = getLocationSlugs()
  const now = new Date()

  if (id === 0) {
    // ── Shard 0: High-value standalone pages (priority 0.6+) ──────────────────
    return [
      { url: BASE, lastModified: now, changeFrequency: 'daily', priority: 1.0 },
      // Tools
      { url: `${BASE}/sobriety-counter`, lastModified: now, changeFrequency: 'monthly', priority: 0.95 },
      { url: `${BASE}/withdrawal-timeline`, lastModified: now, changeFrequency: 'monthly', priority: 0.92 },
      { url: `${BASE}/addiction-cost-calculator`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
      { url: `${BASE}/alcohol-units-calculator`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
      { url: `${BASE}/am-i-an-alcoholic`, lastModified: now, changeFrequency: 'monthly', priority: 0.92 },
      // High-traffic informational
      { url: `${BASE}/how-to-stop-drinking`, lastModified: now, changeFrequency: 'monthly', priority: 0.95 },
      { url: `${BASE}/alcohol-withdrawal-symptoms`, lastModified: now, changeFrequency: 'monthly', priority: 0.93 },
      { url: `${BASE}/heroin-withdrawal-symptoms`, lastModified: now, changeFrequency: 'monthly', priority: 0.92 },
      { url: `${BASE}/what-is-methadone`, lastModified: now, changeFrequency: 'monthly', priority: 0.88 },
      { url: `${BASE}/signs-of-alcoholism`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
      { url: `${BASE}/signs-of-drug-addiction`, lastModified: now, changeFrequency: 'monthly', priority: 0.88 },
      // Drug detection pages
      ...([
        'alcohol','cannabis','cocaine','heroin','mdma','tramadol',
        'ketamine','diazepam','codeine','pregabalin','zopiclone',
        'amphetamine','methamphetamine','buprenorphine',
      ].map(d => ({
        url: `${BASE}/how-long-does-${d}-stay-in-your-system`,
        lastModified: now,
        changeFrequency: 'monthly' as const,
        priority: ['alcohol','cannabis','cocaine','heroin'].includes(d) ? 0.88 : 0.75,
      }))),
      // Trust & E-E-A-T pages
      { url: `${BASE}/about`, lastModified: now, changeFrequency: 'yearly', priority: 0.7 },
      { url: `${BASE}/editorial-policy`, lastModified: now, changeFrequency: 'yearly', priority: 0.65 },
      { url: `${BASE}/privacy-policy`, lastModified: now, changeFrequency: 'yearly', priority: 0.6 },
      { url: `${BASE}/terms`, lastModified: now, changeFrequency: 'yearly', priority: 0.6 },
    ]
  }

  if (id === 1) {
    // ── Shard 1: Core hub pages — /help /rehab /alcohol-rehab /drug-rehab ─────
    return locationEntries([
      { route: 'help', weight: 1.0 },
      { route: 'rehab', weight: 1.0 },
      { route: 'alcohol-rehab', weight: 0.95 },
      { route: 'drug-rehab', weight: 0.95 },
      { route: 'drug-treatment', weight: 0.9 },
      { route: 'private-rehab', weight: 0.88 },
      { route: 'nhs-rehab', weight: 0.85 },
      { route: 'rehab-cost', weight: 0.85 },
      { route: 'detox-centres', weight: 0.85 },
    ], slugs)
  }

  if (id === 2) {
    // ── Shard 2: Substance addiction pages ────────────────────────────────────
    return locationEntries([
      { route: 'alcohol-addiction', weight: 0.92 },
      { route: 'heroin-addiction', weight: 0.9 },
      { route: 'cocaine-addiction', weight: 0.9 },
      { route: 'opiate-addiction', weight: 0.88 },
      { route: 'cannabis-addiction', weight: 0.85 },
      { route: 'crack-cocaine-addiction', weight: 0.85 },
      { route: 'prescription-drug-addiction', weight: 0.85 },
      { route: 'methamphetamine-addiction', weight: 0.8 },
      { route: 'ketamine-addiction', weight: 0.8 },
      { route: 'gambling-addiction', weight: 0.78 },
      { route: 'mdma-ecstasy-addiction', weight: 0.75 },
      { route: 'amphetamine-addiction', weight: 0.75 },
    ], slugs)
  }

  if (id === 3) {
    // ── Shard 3: Prescription drugs & niche substances ────────────────────────
    return locationEntries([
      { route: 'benzodiazepine-addiction', weight: 0.82 },
      { route: 'codeine-addiction', weight: 0.78 },
      { route: 'tramadol-addiction', weight: 0.78 },
      { route: 'diazepam-addiction', weight: 0.75 },
      { route: 'gabapentin-addiction', weight: 0.75 },
      { route: 'pregabalin-addiction', weight: 0.75 },
      { route: 'fentanyl-addiction', weight: 0.72 },
      { route: 'zopiclone-addiction', weight: 0.72 },
      { route: 'painkiller-addiction', weight: 0.78 },
      { route: 'sleeping-pill-addiction', weight: 0.72 },
      { route: 'antidepressant-addiction', weight: 0.68 },
      { route: 'spice-addiction', weight: 0.75 },
      { route: 'nitrous-oxide-addiction', weight: 0.7 },
      { route: 'inhalant-addiction', weight: 0.65 },
      { route: 'eating-disorder-addiction', weight: 0.68 },
    ], slugs)
  }

  if (id === 4) {
    // ── Shard 4: Detox / treatment types ─────────────────────────────────────
    return locationEntries([
      { route: 'alcohol-detox', weight: 0.9 },
      { route: 'drug-detox', weight: 0.88 },
      { route: 'heroin-detox', weight: 0.88 },
      { route: 'residential-rehab', weight: 0.9 },
      { route: 'outpatient-rehab', weight: 0.82 },
      { route: 'online-rehab', weight: 0.75 },
      { route: 'alcohol-counselling', weight: 0.82 },
      { route: 'drug-counselling', weight: 0.8 },
      { route: 'opioid-substitution', weight: 0.82 },
      { route: 'harm-reduction', weight: 0.78 },
      { route: 'naloxone', weight: 0.75 },
      { route: 'sober-living', weight: 0.72 },
    ], slugs)
  }

  if (id === 5) {
    // ── Shard 5: Support groups & mutual aid ──────────────────────────────────
    return locationEntries([
      { route: 'aa-meetings', weight: 0.85 },
      { route: 'na-meetings', weight: 0.82 },
      { route: 'al-anon', weight: 0.8 },
      { route: 'smart-recovery', weight: 0.75 },
      { route: 'cocaine-anonymous', weight: 0.72 },
      { route: '12-step-programme', weight: 0.72 },
      { route: 'non-12-step-rehab', weight: 0.72 },
      { route: 'abstinence-based-rehab', weight: 0.7 },
      { route: 'aftercare', weight: 0.75 },
      { route: 'recovery-coaching', weight: 0.7 },
    ], slugs)
  }

  if (id === 6) {
    // ── Shard 6: Specialist services ──────────────────────────────────────────
    return locationEntries([
      { route: 'dual-diagnosis', weight: 0.85 },
      { route: 'womens-rehab', weight: 0.8 },
      { route: 'teen-addiction', weight: 0.8 },
      { route: 'workplace-addiction', weight: 0.75 },
      { route: 'family-therapy', weight: 0.78 },
      { route: 'how-to-help', weight: 0.75 },
      { route: 'chemsex-support', weight: 0.72 },
      { route: 'binge-drinking', weight: 0.8 },
      { route: 'how-to-help', weight: 0.75 },
    ], slugs)
  }

  if (id === 7) {
    // ── Shard 7: Milestone & sobriety time pages ──────────────────────────────
    const entries: MetadataRoute.Sitemap = []
    // days-sober: 1–3650 (10 years)
    for (let d = 1; d <= 3650; d++) {
      entries.push({
        url: `${BASE}/days-sober/${d}`,
        lastModified: now,
        changeFrequency: 'yearly',
        priority: d <= 30 ? 0.72 : d <= 365 ? 0.65 : d <= 1000 ? 0.58 : 0.45,
      })
    }
    // days-clean: 1–3650
    for (let d = 1; d <= 3650; d++) {
      entries.push({
        url: `${BASE}/days-clean/${d}`,
        lastModified: now,
        changeFrequency: 'yearly',
        priority: d <= 30 ? 0.68 : d <= 365 ? 0.6 : 0.45,
      })
    }
    // weeks-sober: 1–520 (10 years)
    for (let w = 1; w <= 520; w++) {
      entries.push({
        url: `${BASE}/weeks-sober/${w}`,
        lastModified: now,
        changeFrequency: 'yearly',
        priority: w <= 52 ? 0.65 : 0.5,
      })
    }
    // months-sober: 1–120
    for (let m = 1; m <= 120; m++) {
      entries.push({
        url: `${BASE}/months-sober/${m}`,
        lastModified: now,
        changeFrequency: 'yearly',
        priority: [1,3,6,12,18,24,36,60,120].includes(m) ? 0.72 : 0.55,
      })
    }
    // years-sober: 1–50
    for (let y = 1; y <= 50; y++) {
      entries.push({
        url: `${BASE}/years-sober/${y}`,
        lastModified: now,
        changeFrequency: 'yearly',
        priority: [1,2,5,10,20,25,50].includes(y) ? 0.75 : 0.6,
      })
    }
    return entries
  }

  return []
}
