// Thin typed wrapper over the locations JSON data.
// Raw data lives in data/locations.json (generated by scripts/build-locations.js)

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _data = require('../data/locations.json') as {
  total: number
  locations: UKLocation[]
}

export interface UKLocation {
  slug: string
  name: string
  country: 'England' | 'Scotland' | 'Wales' | 'Northern Ireland'
  admin1: string
  admin2: string
  lat: number
  lng: number
  population: number
}

// Build lookup map once at module load
const LOCATION_MAP: Record<string, UKLocation> = Object.fromEntries(
  _data.locations.map((l: UKLocation) => [l.slug, l])
)

export function getLocation(slug: string): UKLocation | null {
  return LOCATION_MAP[slug] ?? null
}

export function getLocationSlugs(): string[] {
  return _data.locations.map((l: UKLocation) => l.slug)
}

/**
 * Returns the top N locations by population, sorted descending.
 * Used in generateStaticParams to control how many pages are pre-built at deploy time.
 *
 * Default: 0 (empty array) — no pages pre-built, all generate on first request via ISR.
 * This keeps the Vercel deployment payload under the 80MB Hobby tier limit.
 * All 3,835 locations are still fully accessible (dynamicParams=true).
 *
 * Pass a limit to pre-build: e.g. getTopLocationSlugs(50) pre-builds the top 50 cities.
 */
export function getTopLocationSlugs(limit = 0): string[] {
  if (limit === 0) return []
  return [..._data.locations]
    .sort((a: UKLocation, b: UKLocation) => b.population - a.population)
    .slice(0, limit)
    .map((l: UKLocation) => l.slug)
}

export function getAllLocations(): UKLocation[] {
  return _data.locations
}

export const totalLocations = _data.total
