// Thin typed wrapper over the locations JSON data.
// Raw data lives in data/locations.json (generated by scripts/build-locations.js)

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _data = require('../data/locations.json') as {
  total: number
  locations: UKLocation[]
}

export interface UKLocation {
  slug: string
  name: string
  country: 'England' | 'Scotland' | 'Wales' | 'Northern Ireland'
  admin1: string
  admin2: string
  lat: number
  lng: number
  population: number
}

// Build lookup map once at module load
const LOCATION_MAP: Record<string, UKLocation> = Object.fromEntries(
  _data.locations.map((l: UKLocation) => [l.slug, l])
)

export function getLocation(slug: string): UKLocation | null {
  return LOCATION_MAP[slug] ?? null
}

export function getLocationSlugs(): string[] {
  return _data.locations.map((l: UKLocation) => l.slug)
}

export function getAllLocations(): UKLocation[] {
  return _data.locations
}

export const totalLocations = _data.total
