import type { SubstanceConfig } from '../components/SubstanceLocationPage'

export const SUBSTANCES: Record<string, SubstanceConfig> = {
  'alcohol-addiction': {
    slug: 'alcohol-addiction',
    name: 'Alcohol',
    nameAdjective: 'alcohol',
    type: 'alcohol',
    signs: [
      'Drinking more than intended or for longer than planned',
      'Being unable to cut down or stop despite wanting to',
      'Spending a lot of time drinking, recovering, or obtaining alcohol',
      'Continuing to drink despite problems with relationships, work, or health',
      'Needing more alcohol to get the same effect (increased tolerance)',
      'Experiencing shaking, sweating, or anxiety when not drinking (withdrawal)',
      'Giving up activities you once enjoyed in favour of drinking',
      'Drinking to relieve or avoid withdrawal symptoms',
    ],
    withdrawal: [
      'Tremors and shaking (typically starting 6–12 hours after the last drink)',
      'Heavy sweating, nausea, and vomiting',
      'Severe anxiety and restlessness',
      'Insomnia and vivid nightmares',
      'Seizures (in severe cases — seek emergency medical help)',
      'Delirium Tremens (DTs) in severe dependency — hallucinations, confusion, fever',
    ],
    treatment: [
      'Medically supervised alcohol detox (essential for severe dependency — DO NOT stop suddenly at home without medical advice)',
      'Residential rehabilitation (28–90 days, NHS or private)',
      'Community alcohol treatment services (free, self-referral via NHS)',
      'Medication: Chlordiazepoxide during detox; Acamprosate (Campral) or Naltrexone to prevent relapse',
      'Psychological therapies: CBT, motivational interviewing, 12-step',
      'AA meetings (free, nationwide, 24/7)',
      'SMART Recovery (non-12-step alternative)',
    ],
    snippet: (loc) => `Alcohol addiction help is available in ${loc} through free NHS community services, residential rehab, and AA meetings. If you or someone you know needs help with alcohol addiction in ${loc}, call Frank free on 0300 123 6600 (24/7). Alcohol dependency can be life-threatening to stop without medical support — always seek advice first.`,
    faqs: (loc) => [
      {
        question: `Where can I get alcohol addiction help in ${loc}?`,
        answer: `Alcohol addiction help in ${loc} is available through your GP (free referral), NHS drug and alcohol services (free, self-referral via Frank 0300 123 6600), private rehab centres, and AA meetings. Treatment options range from community outpatient support to medically supervised residential detox and rehab.`,
      },
      {
        question: `Is it dangerous to stop drinking suddenly?`,
        answer: `Yes. Alcohol withdrawal can be life-threatening for people with severe dependency. Unlike most other drugs, stopping alcohol abruptly without medical supervision can cause life-threatening seizures and Delirium Tremens. Always speak to a GP or call Frank (0300 123 6600) before stopping drinking if you drink heavily every day.`,
      },
      {
        question: `How long does alcohol detox take?`,
        answer: `Alcohol detox typically takes 5–10 days under medical supervision. The most acute symptoms occur in the first 24–72 hours. A supervised detox uses medication (usually chlordiazepoxide) to manage withdrawal safely. After detox, a rehabilitation programme addresses the psychological aspects of alcohol addiction.`,
      },
      {
        question: `Is alcohol addiction treatment free in ${loc}?`,
        answer: `Yes. NHS alcohol treatment in ${loc} is free. You can self-refer or be referred by a GP to your local alcohol service. Community-based treatment, medication-assisted detox, and in some cases residential rehab are all available via the NHS. AA meetings are also always free.`,
      },
      {
        question: `What medication is used for alcohol addiction?`,
        answer: `During detox, chlordiazepoxide (a benzodiazepine) is typically prescribed to prevent seizures and manage withdrawal. For relapse prevention after detox, Acamprosate (Campral) reduces cravings, Naltrexone blocks the reward effect of alcohol, and Disulfiram (Antabuse) causes an unpleasant reaction if you drink. All are available via your GP.`,
      },
      {
        question: `What are the long-term effects of alcohol addiction?`,
        answer: `Long-term alcohol addiction causes liver disease (including cirrhosis), heart disease, increased cancer risk (mouth, throat, oesophagus, liver, breast), brain damage, nerve damage, and mental health disorders including depression and anxiety. Getting help is critical — many of these conditions improve or reverse with sustained sobriety.`,
      },
    ],
  },

  'cocaine-addiction': {
    slug: 'cocaine-addiction',
    name: 'Cocaine',
    nameAdjective: 'cocaine',
    type: 'drug',
    signs: [
      'Using cocaine more frequently or in larger amounts than intended',
      'Inability to stop or cut down despite wanting to',
      'Strong, intense cravings for cocaine',
      'Continuing to use despite financial problems, relationship damage, or health issues',
      'Snorting, smoking (crack), or injecting cocaine',
      'Loss of interest in activities that don\'t involve cocaine',
      'Paranoia, anxiety, or mood swings',
      'Deteriorating physical health — weight loss, nasal damage, skin picking',
    ],
    withdrawal: [
      'Intense cravings for cocaine (often the hardest part)',
      'Extreme fatigue and exhaustion ("crash")',
      'Depression and low mood — can be severe',
      'Increased appetite',
      'Difficulty concentrating',
      'Sleep disturbances — sleeping too much or insomnia',
      'Anxiety and irritability',
      'Suicidal thoughts in some cases — seek help immediately if this occurs',
    ],
    treatment: [
      'Community drug treatment services (free, NHS — no medication licenced for cocaine but therapy is highly effective)',
      'CBT (Cognitive Behavioural Therapy) — the most evidence-based treatment for cocaine addiction',
      'Residential rehabilitation (NHS or private)',
      'NA meetings (free, nationwide)',
      'Contingency management — rewards-based therapy increasingly available on NHS',
      'Addressing underlying mental health issues (dual diagnosis)',
    ],
    snippet: (loc) => `Cocaine addiction help is available in ${loc} through NHS community drug services, private rehab, and NA meetings. There is no licensed medication for cocaine addiction, but CBT (cognitive behavioural therapy) is highly effective. Call Frank free on 0300 123 6600 (24/7) to find cocaine treatment services in ${loc}.`,
    faqs: (loc) => [
      {
        question: `How do I get help for cocaine addiction in ${loc}?`,
        answer: `Contact your local NHS drug service (self-referral is possible — call Frank on 0300 123 6600 to find the right service in ${loc}), speak to your GP, or contact a private rehab centre. Community drug treatment, CBT, NA meetings, and residential rehab are all available and effective for cocaine addiction.`,
      },
      {
        question: `Is cocaine addiction a physical addiction?`,
        answer: `Cocaine addiction is primarily psychological rather than physical. There is no significant physical withdrawal that is medically dangerous. However, the psychological cravings and depression during cocaine withdrawal can be severe and intense. The lack of a severe physical withdrawal often makes people underestimate how hard it is to stop alone — professional support is important.`,
      },
      {
        question: `How long does cocaine stay in your system?`,
        answer: `Cocaine is typically detectable in urine for 2–4 days after use, or up to 10 days for heavy users. In blood, it clears within 12 hours. Hair follicle tests can detect cocaine use for up to 90 days. These windows vary based on frequency of use, metabolism, and method of testing.`,
      },
      {
        question: `Is there medication to help with cocaine addiction?`,
        answer: `There is currently no licensed medication specifically approved for cocaine addiction in the UK. NHS treatment focuses on psychological therapies, especially CBT and motivational interviewing. Some off-label medications are used in clinical settings. Research into new pharmacological treatments is ongoing.`,
      },
      {
        question: `What is crack cocaine addiction?`,
        answer: `Crack cocaine is a smokeable form of cocaine that produces an intense but very short-lived high (5–10 minutes). Because the high is so brief and intense, crack cocaine is considered more addictive than powdered cocaine. Treatment is the same — community drug services, CBT, NA, and residential rehab — but may need to be more intensive.`,
      },
      {
        question: `Can cocaine damage your heart?`,
        answer: `Yes. Cocaine severely stresses the cardiovascular system. It significantly raises heart rate and blood pressure and can cause heart attacks, strokes, and cardiac arrhythmias even in young, healthy people. Cocaine use is one of the leading non-natural causes of cardiac events in adults under 40.`,
      },
    ],
  },

  'heroin-addiction': {
    slug: 'heroin-addiction',
    name: 'Heroin',
    nameAdjective: 'heroin',
    type: 'drug',
    signs: [
      'Using heroin daily or near-daily to prevent withdrawal',
      'Injecting, smoking ("chasing the dragon"), or snorting heroin',
      'Track marks, collapsed veins, or abscesses (if injecting)',
      'Pinpoint pupils and appearing drowsy or "nodding off"',
      'Significant weight loss and neglect of personal hygiene',
      'Stealing or committing crimes to fund heroin use',
      'Withdrawing from family, friends, and social activities',
      'Finding it impossible to stop without severe withdrawal symptoms',
    ],
    withdrawal: [
      'Intense muscle aches and cramps ("flu-like" symptoms)',
      'Sweating, chills, and goosebumps',
      'Nausea, vomiting, and diarrhoea',
      'Severe anxiety and agitation',
      'Insomnia',
      'Strong cravings for heroin',
      'Peaks at 36–72 hours and typically resolves within 7–10 days for physical symptoms',
    ],
    treatment: [
      'Medically supervised opiate detox — vital for safety',
      'Methadone maintenance therapy (MMT) — NHS free, reduces withdrawal, overdose risk, and crime',
      'Buprenorphine (Subutex/Suboxone) — increasingly preferred, can be prescribed by GPs',
      'Naltrexone — blocks heroin\'s effects after detox (implants available)',
      'Residential rehabilitation (NHS or private)',
      'Needle exchange and harm reduction services',
      'NA meetings (free, nationwide)',
    ],
    snippet: (loc) => `Heroin addiction treatment is available in ${loc} through the NHS at no cost. Treatment includes methadone or buprenorphine (Subutex) to manage withdrawal safely, combined with psychological support and rehab. Call Frank free on 0300 123 6600 (24/7) to find heroin treatment services in ${loc} — help is available without judgement.`,
    faqs: (loc) => [
      {
        question: `Where can I get heroin addiction treatment in ${loc}?`,
        answer: `NHS heroin addiction treatment in ${loc} is free and can be accessed by self-referral. Call Frank on 0300 123 6600 to be directed to your local drug service. Treatment includes methadone or buprenorphine prescription, community support, and referral to rehab if needed. You can also speak to your GP directly.`,
      },
      {
        question: `What is the best treatment for heroin addiction?`,
        answer: `The most effective treatment for heroin addiction combines medication-assisted treatment (MAT) — methadone or buprenorphine — with psychological support (CBT, key working, and group therapy). Residential rehabilitation with strong aftercare produces the best long-term outcomes. Both are available through NHS services in ${loc}.`,
      },
      {
        question: `What is methadone and how does it help with heroin addiction?`,
        answer: `Methadone is a long-acting opioid prescribed by NHS drug services to manage heroin withdrawal and reduce cravings. It prevents withdrawal symptoms, dramatically reduces heroin use, and lowers the risk of overdose and blood-borne virus transmission. It is dispensed daily from a pharmacy and is completely free on the NHS.`,
      },
      {
        question: `Is heroin withdrawal dangerous?`,
        answer: `Heroin withdrawal is extremely uncomfortable but is rarely life-threatening in physically healthy adults. However, the severe discomfort drives relapse, and those who do relapse face dramatically heightened overdose risk as their tolerance has dropped. Medically supervised detox with buprenorphine or methadone is strongly recommended and is free via the NHS.`,
      },
      {
        question: `What is the risk of heroin overdose?`,
        answer: `Heroin overdose is a medical emergency. Signs include very slow or stopped breathing, blue lips, pale skin, and unresponsiveness. Call 999 immediately. Naloxone (Narcan) reverses opioid overdose — it is available free from needle exchanges and many pharmacies without a prescription. Anyone who uses heroin should carry naloxone.`,
      },
      {
        question: `Can heroin addiction be treated on the NHS in ${loc}?`,
        answer: `Yes. NHS heroin treatment in ${loc} is free and comprehensive. It includes methadone or buprenorphine prescription to stabilise you, regular appointments with a drug worker, psychological support, needle exchange, and access to residential rehab for those who need it. You can self-refer without going through a GP.`,
      },
    ],
  },

  'cannabis-addiction': {
    slug: 'cannabis-addiction',
    name: 'Cannabis',
    nameAdjective: 'cannabis',
    type: 'drug',
    signs: [
      'Using cannabis daily to feel "normal"',
      'Inability to enjoy activities or socialise without cannabis',
      'Using cannabis despite it causing anxiety, paranoia, or mental health problems',
      'Continuing to use despite work, relationship, or financial problems',
      'Spending significant money on cannabis each week',
      'Failed attempts to cut down or stop',
      'Using stronger forms (high-potency skunk) in increasing amounts',
      'Withdrawal symptoms when not using (irritability, sleep problems, appetite changes)',
    ],
    withdrawal: [
      'Irritability, anger, and anxiety',
      'Difficulty sleeping and vivid dreams',
      'Loss of appetite and nausea',
      'Restlessness and difficulty concentrating',
      'Sweating, headaches, and mild tremors',
      'Strong cravings',
      'Symptoms peak in the first 2–3 days and typically resolve within 1–2 weeks',
    ],
    treatment: [
      'Community drug treatment services (free via NHS)',
      'CBT (Cognitive Behavioural Therapy) — highly effective for cannabis addiction',
      'Motivational enhancement therapy',
      'NA meetings (cannabis addiction is welcomed)',
      'Residential rehabilitation if community treatment is insufficient',
      'Addressing co-occurring mental health issues (anxiety, depression, psychosis)',
    ],
    snippet: (loc) => `Cannabis addiction help is available in ${loc} through free NHS community services and private treatment. High-potency cannabis can cause psychological dependency and is linked to psychosis in some users. Call Frank free on 0300 123 6600 (24/7) or find NHS cannabis treatment services in ${loc}.`,
    faqs: (loc) => [
      {
        question: `Is cannabis actually addictive?`,
        answer: `Yes. Approximately 1 in 10 cannabis users develop a dependency, rising to 1 in 6 for those who start in their teens. High-potency cannabis (skunk) carries a higher risk. Cannabis Use Disorder is a recognised clinical condition — professional treatment is available and effective through NHS services in ${loc}.`,
      },
      {
        question: `How do I get help for cannabis addiction in ${loc}?`,
        answer: `NHS cannabis addiction treatment in ${loc} is free. Contact your local drug and alcohol service directly (find them via Frank on 0300 123 6600 or the NHS service finder) or speak to your GP. CBT is the most effective treatment and is available through community services and private therapists.`,
      },
      {
        question: `Can cannabis cause mental health problems?`,
        answer: `Yes. Heavy or long-term cannabis use — especially high-potency strains — is strongly linked to anxiety, depression, and in some cases, psychosis and schizophrenia. People who start using cannabis in their teens face higher risks. If you are experiencing mental health problems alongside cannabis use, inform your GP — dual diagnosis treatment is available.`,
      },
      {
        question: `What are the withdrawal symptoms from cannabis?`,
        answer: `Cannabis withdrawal symptoms include irritability, anxiety, sleep problems, vivid dreams, sweating, reduced appetite, and cravings. They typically begin within 24 hours of stopping, peak at 2–3 days, and resolve within 1–2 weeks. Unlike alcohol, cannabis withdrawal is uncomfortable but not medically dangerous.`,
      },
      {
        question: `How long does cannabis stay in your system?`,
        answer: `Cannabis (THC) is detectable in urine for 3–30 days after use, depending on frequency. Occasional users clear it in 3–5 days; daily heavy users may test positive for up to 30 days. In blood, THC typically clears within 1–7 days. Hair follicle tests can detect use for up to 90 days.`,
      },
      {
        question: `Does smoking cannabis affect your lungs?`,
        answer: `Yes. Smoking cannabis (particularly mixed with tobacco) is linked to bronchitis, respiratory infections, and increased lung cancer risk. Vaporising cannabis reduces some respiratory risks but does not eliminate them. The mental health risks of high-potency cannabis remain regardless of method of consumption.`,
      },
    ],
  },
}

// Shorter configs for the remaining substances
export const SUBSTANCE_CONFIGS: Record<string, SubstanceConfig> = {
  ...SUBSTANCES,

  'prescription-drug-addiction': {
    slug: 'prescription-drug-addiction',
    name: 'Prescription Drugs',
    nameAdjective: 'prescription drug',
    type: 'drug',
    signs: [
      'Taking prescription medication in larger doses than prescribed',
      'Taking medication prescribed for someone else',
      'Seeking prescriptions from multiple doctors ("prescription shopping")',
      'Continuing to use medication after the problem it was prescribed for has resolved',
      'Feeling unable to function or cope without the medication',
      'Hiding medication use from family members and healthcare providers',
      'Experiencing withdrawal symptoms when doses are reduced',
    ],
    withdrawal: [
      'Withdrawal varies significantly by medication type (opioids, benzodiazepines, stimulants)',
      'Benzodiazepine withdrawal can be life-threatening — never stop abruptly without medical advice',
      'Opioid withdrawal: flu-like symptoms, muscle cramps, agitation (rarely life-threatening)',
      'Rebound anxiety, depression, and insomnia',
      'Physical and psychological cravings',
      'Always seek medical supervision before reducing or stopping prescribed medication',
    ],
    treatment: [
      'GP-managed tapering (gradual dose reduction under medical supervision)',
      'NHS drug service support for prescription opioids',
      'Specialist benzodiazepine withdrawal clinics for complex cases',
      'CBT and psychological therapy',
      'NA meetings',
      'Residential rehab if outpatient treatment is insufficient',
    ],
    snippet: (loc) => `Prescription drug addiction (including opioids, benzodiazepines, and stimulants) is treated in ${loc} through NHS community drug services and private rehab. Never stop prescription medication suddenly — speak to your GP first. Call Frank on 0300 123 6600 (free, 24/7) for guidance on prescription drug addiction services in ${loc}.`,
    faqs: (loc) => [
      {
        question: `Is it possible to become addicted to prescription medication?`,
        answer: `Yes. Prescription opioids (codeine, tramadol, oxycodone), benzodiazepines (diazepam, lorazepam), and stimulants (methylphenidate) all carry a risk of dependency, particularly with long-term use. Addiction to prescribed medication is a recognised medical condition and is treated without judgement through NHS services in ${loc}.`,
      },
      {
        question: `Is it safe to stop taking benzodiazepines suddenly?`,
        answer: `No. Stopping benzodiazepines abruptly can cause life-threatening seizures. This is similar to alcohol withdrawal. Always speak to your GP before reducing or stopping benzodiazepines — a gradual tapering schedule under medical supervision is essential. NHS services in ${loc} can help manage this safely.`,
      },
      {
        question: `Where do I get help for prescription drug addiction in ${loc}?`,
        answer: `Speak to your GP, who can manage a safe tapering schedule and refer you to specialist services. You can also self-refer to your local drug service - call Frank on 0300 123 6600 to find services in ${loc}. Private rehab specialising in prescription drug dependency is also available.`,
      },
      {
        question: `I was prescribed this medication by my doctor — can I still be addicted?`,
        answer: `Yes. Dependency can develop even when medication is used exactly as prescribed. This is especially common with opioids and benzodiazepines taken over extended periods. Being physically dependent does not mean you did something wrong. Your GP or a drug service can help you reduce safely without judgement.`,
      },
    ],
  },

  'ketamine-addiction': {
    slug: 'ketamine-addiction',
    name: 'Ketamine',
    nameAdjective: 'ketamine',
    type: 'drug',
    signs: [
      'Using ketamine several times a week or daily',
      'Needing larger amounts to get the same effect',
      'Experiencing bladder or kidney problems (a serious sign of heavy use)',
      'Dissociation from reality or difficulty distinguishing real from unreal',
      'Continuing to use despite health warnings from doctors',
      'Using alone and hiding use from others',
    ],
    withdrawal: [
      'Intense cravings',
      'Anxiety, depression, and agitation',
      'Cognitive difficulties and confusion',
      'Fatigue and insomnia',
      'Tremors and sweating',
      'No physical withdrawal comparable to opioids or alcohol, but psychological dependency can be severe',
    ],
    treatment: [
      'Community drug treatment services (NHS, free)',
      'CBT and psychological therapy — most effective for ketamine addiction',
      'Bladder/kidney monitoring and medical treatment for ketamine cystitis',
      'Residential rehabilitation',
      'NA meetings',
    ],
    snippet: (loc) => `Ketamine addiction treatment is available in ${loc} through NHS drug services and private rehab. Heavy ketamine use can permanently damage the bladder and kidneys. Call Frank on 0300 123 6600 (free, 24/7) to find ketamine addiction help in ${loc}.`,
    faqs: (loc) => [
      {
        question: `Can ketamine damage your bladder?`,
        answer: `Yes. Heavy ketamine use causes ketamine-induced uropathy (ketamine bladder syndrome) — characterised by severe bladder pain, frequent urination, and in serious cases, bladder shrinkage requiring surgery. This is one of the most serious and distinctive health consequences of ketamine addiction. Stopping ketamine use can halt further damage.`,
      },
      {
        question: `Where can I get ketamine addiction help in ${loc}?`,
        answer: `NHS drug and alcohol services in ${loc} treat ketamine addiction. Self-refer by calling Frank on 0300 123 6600. If you have bladder symptoms, ask your GP for a urology referral alongside addiction treatment. Private rehab specialising in ketamine dependency is also available.`,
      },
      {
        question: `Is ketamine addiction common?`,
        answer: `Ketamine use and dependency has risen sharply in the UK, particularly among young adults in club culture. It is now regularly seen in NHS drug treatment services. Psychological dependency is common among regular users, and long-term health consequences — particularly bladder damage — can be severe.`,
      },
    ],
  },

  'benzodiazepine-addiction': {
    slug: 'benzodiazepine-addiction',
    name: 'Benzodiazepines',
    nameAdjective: 'benzodiazepine',
    type: 'drug',
    signs: [
      'Taking benzodiazepines more frequently or in higher doses than prescribed',
      'Feeling unable to cope with anxiety or sleep without them',
      'Seeking prescriptions from multiple sources',
      'Taking benzodiazepines not prescribed to you (diazepam, xanax, etc.)',
      'Memory problems or confusion (common side effect at high doses)',
      'Hiding use from your GP or family',
    ],
    withdrawal: [
      'SEVERE — benzodiazepine withdrawal can cause life-threatening seizures',
      'Extreme anxiety and panic attacks',
      'Insomnia and sleep disturbances',
      'Tremors and sweating',
      'Hallucinations and perceptual disturbances',
      'Psychosis in severe cases',
      'NEVER stop benzodiazepines suddenly without medical supervision',
    ],
    treatment: [
      'URGENT: Always consult a GP before reducing or stopping — tapering is essential for safety',
      'Gradual GP-managed diazepam substitution and tapering',
      'NHS specialist benzodiazepine withdrawal clinics',
      'CBT for underlying anxiety disorders',
      'Residential detox (for severe or complex dependency)',
      'Long-term psychological support',
    ],
    snippet: (loc) => `Benzodiazepine addiction (diazepam, lorazepam, alprazolam/Xanax) is treated in ${loc} via NHS drug services and specialist clinics. Stopping benzos suddenly can cause life-threatening seizures — never stop without medical advice. Call Frank on 0300 123 6600 (free, 24/7) or speak to your GP immediately for benzodiazepine help in ${loc}.`,
    faqs: (loc) => [
      {
        question: `Why is stopping benzodiazepines dangerous?`,
        answer: `Benzodiazepines work on the same GABA receptors in the brain as alcohol. Like alcohol, sudden cessation can cause life-threatening seizures in people who are physically dependent. It is essential to reduce gradually under medical supervision using a tapering protocol — typically substituting shorter-acting benzos (Xanax) with longer-acting diazepam before slowly reducing.`,
      },
      {
        question: `How do I get help for benzodiazepine addiction in ${loc}?`,
        answer: `Speak to your GP immediately — this is the safest first step. Your GP can arrange a supervised diazepam tapering schedule. You can also self-refer to NHS drug services in ${loc} via Frank (0300 123 6600). For severe dependency, inpatient medically supervised detox may be recommended.`,
      },
      {
        question: `How long does benzodiazepine withdrawal last?`,
        answer: `Benzo withdrawal is notoriously prolonged. Acute withdrawal from short-acting benzodiazepines (Xanax, Ativan) can begin within 6–8 hours and last 2–4 weeks. Long-acting benzodiazepines (Diazepam) have a slower onset. Some people experience PAWS (post-acute withdrawal syndrome) with symptoms lasting months — slow tapering minimises this.`,
      },
    ],
  },

  'methamphetamine-addiction': {
    slug: 'methamphetamine-addiction',
    name: 'Methamphetamine',
    nameAdjective: 'methamphetamine',
    type: 'drug',
    signs: [
      'Using meth daily or in binges ("runs")',
      'Significant and rapid weight loss',
      'Severe dental decay ("meth mouth")',
      'Skin sores from compulsive picking',
      'Extreme paranoia, aggression, or psychosis',
      'Staying awake for days at a time followed by long crash periods',
      'Neglect of personal hygiene and responsibilities',
    ],
    withdrawal: [
      'Extreme fatigue and prolonged sleep (the "crash")',
      'Severe depression — can include suicidal thoughts',
      'Increased appetite',
      'Intense cravings',
      'Anxiety, irritability, and agitation',
      'Cognitive difficulties that can persist for months',
    ],
    treatment: [
      'Community drug treatment services (NHS, free)',
      'CBT — the most evidence-based treatment for meth addiction',
      'Contingency management (rewards-based therapy)',
      'Residential rehabilitation',
      'Mental health support — meth-induced psychosis can persist after stopping',
      'NA meetings',
    ],
    snippet: (loc) => `Methamphetamine (crystal meth) addiction treatment is available in ${loc} through NHS drug services and private rehab. Meth can cause severe psychiatric symptoms including paranoia and psychosis. Call Frank on 0300 123 6600 (free, 24/7) to find methamphetamine addiction help in ${loc}.`,
    faqs: (loc) => [
      {
        question: `How do I get help for methamphetamine addiction in ${loc}?`,
        answer: `NHS drug treatment services in ${loc} treat methamphetamine addiction. Call Frank on 0300 123 6600 (free, 24/7) for a referral to your local service. CBT and contingency management are the most effective treatments. If you are experiencing psychosis, go to A&E or call 999.`,
      },
      {
        question: `Can methamphetamine cause psychosis?`,
        answer: `Yes. Methamphetamine can trigger psychosis — hallucinations, paranoid delusions, and erratic behaviour — both during use and in withdrawal. Meth-induced psychosis can persist for weeks or months after stopping. If you or someone you know is experiencing psychosis, call 999 or go to A&E immediately.`,
      },
      {
        question: `Is crystal meth common in the UK?`,
        answer: `Methamphetamine use has historically been lower in the UK than in the US, but use has been rising — particularly within chemsex culture. NHS drug services across the UK, including ${loc}, are experienced in treating methamphetamine addiction and offer non-judgemental, confidential support.`,
      },
    ],
  },

  // ── Specific prescription drug addiction pages ───────────────────────────────

  'tramadol-addiction': {
    slug: 'tramadol-addiction',
    name: 'Tramadol',
    nameAdjective: 'tramadol',
    type: 'drug',
    signs: [
      'Taking tramadol more frequently than prescribed or in higher doses',
      'Seeking additional tramadol prescriptions from different doctors',
      'Continuing to take tramadol long after the original pain has resolved',
      'Feeling unable to cope with pain, anxiety, or daily life without tramadol',
      'Buying tramadol online without a prescription',
      'Experiencing withdrawal symptoms when doses are missed (sweating, cramps, anxiety)',
      'Hiding tramadol use from family or healthcare providers',
    ],
    withdrawal: [
      'Flu-like symptoms: sweating, chills, muscle aches, and cramps',
      'Intense anxiety and restlessness',
      'Nausea, vomiting, and diarrhoea',
      'Insomnia and vivid nightmares',
      'Strong cravings for tramadol',
      'Unusual symptoms: tingling, electric-shock sensations, hallucinations (tramadol-specific)',
      'Rarely: seizures — seek medical advice before stopping',
    ],
    treatment: [
      'GP-managed tapering (gradual dose reduction — do NOT stop suddenly)',
      'Buprenorphine or methadone if dependency is severe',
      'NHS community drug service support',
      'CBT for pain coping strategies and addiction',
      'Pain management referral if chronic pain underlies the dependency',
      'NA meetings',
    ],
    snippet: (loc) => `Tramadol addiction treatment is available in ${loc} through NHS community drug services and your GP. Tramadol is a prescription opioid that is increasingly causing dependency across the UK — it should never be stopped suddenly. Call Frank on 0300 123 6600 (free, 24/7) or speak to your GP for tramadol addiction help in ${loc}.`,
    faqs: (loc) => [
      { question: `Is tramadol addictive?`, answer: `Yes. Tramadol is an opioid painkiller and carries a significant risk of physical and psychological dependency, particularly with long-term use. It is increasingly being seen in NHS drug treatment services across ${loc} and the wider UK. Tramadol dependency can develop even when the medication is taken exactly as prescribed.` },
      { question: `How do I get help for tramadol addiction in ${loc}?`, answer: `Speak to your GP — this is the safest first step. They can arrange a safe tapering schedule and refer you to specialist services. You can also self-refer to NHS drug services in ${loc} via Frank (0300 123 6600). Do not stop tramadol suddenly — withdrawal should always be medically supervised.` },
      { question: `What are tramadol withdrawal symptoms?`, answer: `Tramadol withdrawal includes typical opioid symptoms (muscle aches, sweating, chills, nausea, insomnia, anxiety) plus some unusual symptoms specific to tramadol due to its effects on serotonin — including hallucinations, agitation, and electric-shock-like sensations. In rare cases, tramadol withdrawal can cause seizures.` },
      { question: `Can you buy tramadol without a prescription?`, answer: `No — tramadol is a Class C controlled drug in the UK and requires a prescription. It is illegal to possess without a prescription and illegal to supply. Despite this, tramadol is widely available online and is frequently seized by UK Border Force.` },
    ],
  },

  'codeine-addiction': {
    slug: 'codeine-addiction',
    name: 'Codeine',
    nameAdjective: 'codeine',
    type: 'drug',
    signs: [
      'Taking codeine-based products (co-codamol, codeine linctus, Nurofen Plus) daily',
      'Buying multiple packets of over-the-counter codeine products from different pharmacies',
      'Hiding codeine use or taking more than the recommended dose',
      'Feeling unable to manage pain, anxiety, or daily stress without codeine',
      'Continuing to use codeine long after the original reason for taking it has resolved',
      'Experiencing withdrawal symptoms when codeine wears off',
    ],
    withdrawal: [
      'Restlessness, anxiety, and irritability',
      'Muscle aches and stomach cramps',
      'Sweating, chills, and goosebumps',
      'Nausea, vomiting, and diarrhoea',
      'Insomnia',
      'Strong cravings',
      'Symptoms typically resolve within 5–10 days but psychological cravings persist longer',
    ],
    treatment: [
      'GP-managed tapering (gradual reduction in dose)',
      'NHS drug service — codeine dependency is commonly treated',
      'Lower-potency pain relief under medical supervision during taper',
      'CBT to address underlying pain or anxiety driving the dependency',
      'NA meetings',
    ],
    snippet: (loc) => `Codeine addiction is increasingly common in the UK, often beginning with over-the-counter products like co-codamol or Nurofen Plus. Free treatment is available in ${loc} through your GP and NHS drug services. Call Frank on 0300 123 6600 (24/7) for confidential codeine addiction help in ${loc}.`,
    faqs: (loc) => [
      { question: `Is codeine addictive?`, answer: `Yes. Codeine is an opioid and dependency can develop even with over-the-counter doses taken regularly. "OTC codeine addiction" (to products like co-codamol or Nurofen Plus) is widely reported across the UK. The combination with ibuprofen or paracetamol in OTC products also causes liver and kidney damage with long-term heavy use.` },
      { question: `How do I get codeine addiction help in ${loc}?`, answer: `Your GP is the best starting point — they can arrange a safe tapering schedule and refer you to specialist services. You can also self-refer to NHS drug services in ${loc} by calling Frank on 0300 123 6600. Codeine dependency is a recognised medical condition and is treated without judgement.` },
      { question: `What happens if you take too much codeine long-term?`, answer: `Long-term heavy codeine use causes physical dependency, liver damage (from the paracetamol or ibuprofen combined in OTC products), kidney damage, constipation, and hormonal imbalances. It also poses overdose risk — especially when taken with alcohol or other depressants.` },
      { question: `Can you get codeine without a prescription?`, answer: `Low-dose codeine (up to 12.8mg per tablet) is available over the counter in combined products like co-codamol. However, purchasing larger quantities repeatedly from multiple pharmacies is illegal under UK law. Higher-dose codeine always requires a prescription.` },
    ],
  },

  'diazepam-addiction': {
    slug: 'diazepam-addiction',
    name: 'Diazepam',
    nameAdjective: 'diazepam',
    type: 'drug',
    signs: [
      'Taking diazepam (Valium) daily or multiple times per day',
      'Needing increasing doses to get the same effect',
      'Using diazepam obtained online or from street sources',
      'Feeling extreme anxiety when diazepam is not available',
      'Hiding use from your GP or family',
      'Taking diazepam prescribed to someone else',
    ],
    withdrawal: [
      'SEVERE — diazepam withdrawal can cause life-threatening seizures',
      'Extreme anxiety and panic attacks',
      'Tremors and sweating',
      'Insomnia',
      'Confusion and disorientation',
      'Hallucinations',
      'NEVER stop diazepam suddenly — always taper under medical supervision',
    ],
    treatment: [
      'CRITICAL: Speak to your GP before reducing or stopping — do NOT stop suddenly',
      'GP-managed diazepam tapering (switching to a lower dose and gradually reducing)',
      'NHS specialist benzo withdrawal clinic (for complex or high-dose cases)',
      'CBT for anxiety — addresses the underlying driver of diazepam use',
      'Long-term psychological and community support',
    ],
    snippet: (loc) => `Diazepam (Valium) addiction is treated in ${loc} through GP-managed tapering and NHS drug services. Stopping diazepam suddenly can cause life-threatening seizures — never stop without medical advice. Call Frank on 0300 123 6600 (free, 24/7) or speak to your GP for safe diazepam addiction help in ${loc}.`,
    faqs: (loc) => [
      { question: `Is it dangerous to stop diazepam suddenly?`, answer: `Yes — extremely. Diazepam withdrawal can cause potentially fatal seizures in people who are physically dependent. This risk is similar to alcohol withdrawal. Always speak to your GP before reducing or stopping diazepam. A slow taper under medical supervision is essential. NHS services in ${loc} can manage this safely.` },
      { question: `How do I get diazepam addiction help in ${loc}?`, answer: `Speak to your GP immediately — safely managing diazepam withdrawal requires medical supervision. Your GP can arrange a tapering schedule (usually diazepam-to-diazepam, reducing by small amounts over weeks or months). Call Frank (0300 123 6600) to find NHS drug services in ${loc} if you need additional support.` },
      { question: `How long does diazepam withdrawal take?`, answer: `Because diazepam has a very long half-life (20–100 hours), withdrawal is often prolonged. Acute symptoms typically begin 2–7 days after the last dose and can persist for 2–4 weeks. PAWS (post-acute withdrawal syndrome) including anxiety, insomnia, and cognitive difficulties can last months.` },
    ],
  },

  'gabapentin-addiction': {
    slug: 'gabapentin-addiction',
    name: 'Gabapentin',
    nameAdjective: 'gabapentin',
    type: 'drug',
    signs: [
      'Taking gabapentin in higher doses than prescribed or more frequently',
      'Experiencing euphoria or intoxication from gabapentin (especially combined with opioids)',
      'Seeking gabapentin prescriptions from multiple GPs',
      'Buying gabapentin online without a prescription',
      'Feeling unable to function without gabapentin',
      'Experiencing withdrawal when doses are missed',
    ],
    withdrawal: [
      'Anxiety, restlessness, and agitation',
      'Sweating and tremors',
      'Insomnia',
      'Nausea and stomach discomfort',
      'Seizures in some cases — particularly with high-dose use',
      'Never stop gabapentin suddenly without medical advice',
    ],
    treatment: [
      'GP-managed tapering (gradual dose reduction)',
      'NHS drug service support',
      'CBT for anxiety, pain, or the underlying drivers of use',
      'Monitoring for seizure risk during tapering',
    ],
    snippet: (loc) => `Gabapentin (Neurontin) addiction has become a significant issue across the UK, particularly among people who also use opioids. Free help is available in ${loc} through NHS drug services and your GP. Call Frank on 0300 123 6600 (24/7) for gabapentin addiction support in ${loc}.`,
    faqs: (loc) => [
      { question: `Is gabapentin addictive?`, answer: `Yes. Gabapentin (sold as Neurontin) became a Class C controlled drug in the UK in 2019 specifically because of its abuse potential. It is especially dangerous in combination with opioids (heroin, methadone, tramadol), where it significantly increases overdose risk. Dependency can develop relatively quickly, particularly in people with a history of substance use.` },
      { question: `Why was gabapentin made a controlled drug?`, answer: `Gabapentin was reclassified as a Class C controlled drug in the UK in April 2019, alongside pregabalin. This was due to evidence of widespread misuse — particularly its use to enhance the effects of opioids — and a rising number of gabapentin-linked deaths. Possessing gabapentin without a prescription is now a criminal offence.` },
      { question: `How do I get gabapentin addiction help in ${loc}?`, answer: `Speak to your GP — they can arrange a safe tapering schedule. You can also contact NHS drug services in ${loc} via Frank (0300 123 6600). Gabapentin withdrawal should always be managed medically, particularly if you are also using opioids.` },
    ],
  },

  'pregabalin-addiction': {
    slug: 'pregabalin-addiction',
    name: 'Pregabalin',
    nameAdjective: 'pregabalin',
    type: 'drug',
    signs: [
      'Taking pregabalin (Lyrica) in higher doses than prescribed',
      'Using pregabalin to enhance the effects of other drugs (especially opioids)',
      'Seeking pregabalin from multiple prescribers or online sources',
      'Feeling anxious, depressed, or physically unwell when pregabalin is not available',
      'Hiding pregabalin use from family or healthcare providers',
    ],
    withdrawal: [
      'Anxiety, agitation, and restlessness',
      'Sweating and tremors',
      'Insomnia and nightmares',
      'Nausea and stomach pain',
      'Increased risk of seizures — always taper medically',
      'Rebound pain if pregabalin was prescribed for nerve pain',
    ],
    treatment: [
      'GP-managed gradual tapering',
      'NHS drug service involvement, especially if poly-drug use is involved',
      'Pain management referral if chronic nerve pain underlies use',
      'CBT for anxiety',
      'Opioid treatment service if combined opioid dependency exists',
    ],
    snippet: (loc) => `Pregabalin (Lyrica) addiction is a growing crisis in the UK — it became a controlled drug in 2019 due to widespread misuse. Free help is available in ${loc} through NHS drug services. Call Frank on 0300 123 6600 (24/7) for pregabalin addiction support in ${loc}.`,
    faqs: (loc) => [
      { question: `Why is pregabalin so addictive?`, answer: `Pregabalin produces calming, euphoric, and intoxicating effects at higher doses — particularly when combined with opioids, alcohol, or other depressants. This makes it highly appealing as a recreational drug. The UK has seen a sharp rise in pregabalin-related deaths, particularly in areas with high opioid use, leading to its reclassification as a Schedule 3 controlled drug.` },
      { question: `How do I get pregabalin addiction help in ${loc}?`, answer: `Speak to your GP — they can manage a safe tapering plan. NHS drug services in ${loc} (find via Frank: 0300 123 6600) can provide specialist support, particularly if pregabalin is being used alongside opioids. Never stop pregabalin suddenly, as seizure risk is real.` },
      { question: `Is pregabalin the same as gabapentin?`, answer: `Pregabalin (Lyrica) and gabapentin (Neurontin) are both gabapentinoids — they work on the same receptors in the brain and spine. Pregabalin is generally considered more potent and faster-acting, making it more prone to misuse. Both became Class C controlled drugs in the UK in April 2019.` },
    ],
  },

  'zopiclone-addiction': {
    slug: 'zopiclone-addiction',
    name: 'Zopiclone',
    nameAdjective: 'zopiclone',
    type: 'drug',
    signs: [
      'Taking zopiclone every night and being unable to sleep without it',
      'Taking higher doses than prescribed for stronger sedation',
      'Seeking repeat prescriptions or buying zopiclone online',
      'Feeling anxious, restless, or unable to sleep if zopiclone is not available',
      'Using zopiclone during the day or combining with alcohol for a greater effect',
      'Hiding zopiclone use from your GP',
    ],
    withdrawal: [
      'Severe rebound insomnia (often worse than original sleep problem)',
      'Anxiety and panic attacks',
      'Tremors and sweating',
      'Nausea',
      'Seizures in severe cases — taper medically',
      'Perceptual disturbances and nightmares',
    ],
    treatment: [
      'GP-managed gradual tapering (diazepam substitution used for complex cases)',
      'Sleep hygiene and CBT for Insomnia (CBT-I) — highly effective and recommended by NICE',
      'NHS drug service support',
      'Psychological therapy to address underlying anxiety or sleep disorders',
    ],
    snippet: (loc) => `Zopiclone addiction is common in the UK, particularly among people prescribed it for insomnia who become dependent over months or years. Free help is available in ${loc} through your GP and NHS services. Never stop zopiclone suddenly — withdrawal should be medically supervised. Call Frank on 0300 123 6600 (24/7) for zopiclone addiction help in ${loc}.`,
    faqs: (loc) => [
      { question: `Is zopiclone addictive?`, answer: `Yes. The British National Formulary recommends zopiclone be prescribed for no longer than 4 weeks. Long-term use leads to physical dependency where the brain can no longer initiate sleep without the drug. This is a recognised NHS issue and can be treated safely through community services in ${loc}.` },
      { question: `How do I stop zopiclone safely?`, answer: `Stopping zopiclone should always be done gradually under medical supervision. Your GP can arrange a tapering plan, reducing the dose slowly over weeks. In complex cases, switching to diazepam and then tapering is used. CBT for Insomnia (CBT-I) is recommended by NICE as the most effective long-term treatment for insomnia without medication.` },
      { question: `How do I get zopiclone addiction help in ${loc}?`, answer: `Speak to your GP — they can begin a tapering plan and refer you to sleep services or drug services if needed. You can also contact NHS drug services in ${loc} via Frank (0300 123 6600). Zopiclone dependency is very common and treated without judgement.` },
    ],
  },

  'fentanyl-addiction': {
    slug: 'fentanyl-addiction',
    name: 'Fentanyl',
    nameAdjective: 'fentanyl',
    type: 'drug',
    signs: [
      'Using fentanyl patches in ways other than prescribed (chewing, extracting gel)',
      'Using illicit fentanyl (increasingly found in street drugs in the UK)',
      'Needing fentanyl to prevent severe withdrawal',
      'Criminal activity to obtain fentanyl or money to buy it',
      'Extremely pinpoint pupils, frequent nodding off, slow breathing',
      'History of opioid use disorder escalating to fentanyl',
    ],
    withdrawal: [
      'Extremely intense opioid withdrawal due to high potency',
      'Severe muscle cramps, sweating, vomiting, and diarrhoea',
      'Intense anxiety and agitation',
      'Rapid heart rate and elevated blood pressure',
      'Strong cravings',
      'Medical supervision is essential — fentanyl dependency is extremely difficult to manage without medication',
    ],
    treatment: [
      'Medically supervised detox — essential for fentanyl dependency',
      'High-dose methadone or buprenorphine to manage withdrawal',
      'Naloxone (Narcan) — must be carried by anyone using fentanyl. Free from needle exchanges.',
      'Residential rehabilitation',
      'Long-term MAT (Medication-Assisted Treatment)',
      'NHS specialist drug services',
    ],
    snippet: (loc) => `Fentanyl is 50–100 times more potent than morphine and carries an extreme overdose risk. Fentanyl addiction treatment is available in ${loc} through the NHS. If someone has overdosed on fentanyl, call 999 immediately and administer Naloxone if available. Call Frank on 0300 123 6600 (24/7) for urgent fentanyl addiction help in ${loc}.`,
    faqs: (loc) => [
      { question: `How dangerous is fentanyl?`, answer: `Fentanyl is 50–100 times more potent than morphine and 50 times more potent than heroin. A dose of just 2 milligrams (invisible to the naked eye) can be lethal. Illicit fentanyl is increasingly found in street drugs in the UK — including pressed pills and powders sold as other drugs — making every use potentially fatal.` },
      { question: `Is there naloxone for fentanyl overdose?`, answer: `Yes, but multiple doses may be required. Standard naloxone doses reverse fentanyl overdose but due to fentanyl's extreme potency, multiple doses or a continuous naloxone infusion via IV (in hospital) may be needed. Anyone who uses opioids in the UK should carry naloxone — available free from needle exchanges and many pharmacies.` },
      { question: `How do I get fentanyl addiction help in ${loc}?`, answer: `This is urgent. NHS drug treatment services in ${loc} treat fentanyl dependency with high-dose methadone or buprenorphine. Call Frank immediately on 0300 123 6600 (free, 24/7) to be directed to your nearest service. If someone has used fentanyl and is unresponsive or breathing very slowly — call 999 immediately.` },
    ],
  },

  // ── Additional substances ────────────────────────────────────────────────────

  'crack-cocaine-addiction': {
    slug: 'crack-cocaine-addiction',
    name: 'Crack Cocaine',
    nameAdjective: 'crack cocaine',
    type: 'drug',
    signs: [
      'Smoking crack cocaine using a pipe, foil, or improvised device',
      'Extremely short-lived but intense highs (5–10 minutes) followed by an immediate crash',
      'Compulsive redosing — using again immediately after the high wears off',
      'Rapid weight loss and neglect of food, hygiene, and housing',
      'Engaging in risky or criminal behaviour to fund crack use',
      'Paranoia and aggression, particularly when "craving"',
      'Burn marks on fingers or lips from crack pipes',
      'Disappearing for days at a time during "crack runs"',
    ],
    withdrawal: [
      'Extreme fatigue and exhaustion after a crack run',
      'Severe depression — can feel physically painful',
      'Intense, overwhelming cravings (among the strongest of any substance)',
      'Increased appetite',
      'Agitation and irritability',
      'Difficulty concentrating and cognitive fog',
      'Suicidal thoughts in some cases — seek help immediately',
    ],
    treatment: [
      'NHS community drug treatment services (free — crack cocaine is widely treated)',
      'CBT (Cognitive Behavioural Therapy) — most evidence-based treatment',
      'Contingency management (rewards-based therapy) — increasingly available on NHS',
      'Residential rehabilitation (NHS-funded or private)',
      'Cocaine Anonymous (CA) or Narcotics Anonymous (NA) meetings',
      'Intensive case management for those with complex needs (housing, mental health)',
    ],
    snippet: (loc) => `Crack cocaine addiction treatment is available in ${loc} through the NHS at no cost. Crack cocaine is a smokeable, highly addictive form of cocaine that produces an intense but brief high. The compulsive need to redose makes it one of the most difficult addictions to break alone. Call Frank on 0300 123 6600 (free, 24/7) for crack cocaine help in ${loc}.`,
    faqs: (loc) => [
      { question: `How do I get crack cocaine addiction help in ${loc}?`, answer: `NHS drug treatment services in ${loc} provide free, confidential help for crack cocaine addiction. You can self-refer by calling Frank on 0300 123 6600. Treatment includes CBT, keyworking, contingency management, and access to residential rehabilitation. Cocaine Anonymous (CA) and NA meetings provide free peer support.` },
      { question: `Is crack cocaine more addictive than powder cocaine?`, answer: `Yes. Crack cocaine produces a more rapid, intense high when smoked — but lasts only 5–10 minutes. This intensity and brevity drives compulsive redosing in a way that powder cocaine typically does not. The route of administration (smoking) also delivers the drug more rapidly to the brain, increasing addictive potential.` },
      { question: `What is the difference between crack cocaine and cocaine?`, answer: `Crack cocaine is freebase cocaine — powder cocaine that has been chemically processed with baking soda and water to create a smokeable rock. The effects are chemically identical, but the route of administration (smoking vs snorting) and the speed of delivery to the brain make crack significantly more addictive and carry greater health risks.` },
      { question: `Can crack cocaine cause psychosis?`, answer: `Yes. Heavy crack cocaine use can cause cocaine-induced psychosis — characterised by paranoid delusions, hallucinations, and extreme agitation. This is a psychiatric emergency. Call 999 if someone is experiencing psychosis. Crack-induced psychosis typically resolves with abstinence and medical support.` },
      { question: `Is crack cocaine addiction treated on the NHS in ${loc}?`, answer: `Yes. NHS drug services in ${loc} treat crack cocaine addiction as a clinical priority. Treatment is free, confidential, and self-referral is possible. Call Frank on 0300 123 6600 to be connected to the right service in ${loc}.` },
    ],
  },

  'spice-addiction': {
    slug: 'spice-addiction',
    name: 'Spice (Synthetic Cannabis)',
    nameAdjective: 'spice',
    type: 'drug',
    signs: [
      'Smoking spice (synthetic cannabinoids) multiple times daily',
      'Inability to function without spice',
      'Extreme mood swings and aggression',
      'Paranoia, psychosis, or hallucinations',
      'Collapse or "zombie-like" episodes (loss of consciousness or awareness)',
      'Rapid physical deterioration — weight loss, skin and dental problems',
      'Using spice despite multiple medical emergencies',
    ],
    withdrawal: [
      'Severe anxiety and agitation',
      'Profuse sweating and tremors',
      'Nausea, vomiting, and muscle aches',
      'Insomnia',
      'Psychological cravings — often extremely intense',
      'Can be severe and prolonged — worse than cannabis withdrawal',
    ],
    treatment: [
      'NHS drug treatment services — spice is increasingly common in treatment settings',
      'Medically supervised withdrawal if symptoms are severe',
      'Psychiatric assessment and treatment (psychosis is common)',
      'CBT and psychological therapy',
      'Harm reduction — spice users are often rough sleepers or homeless',
      'Housing and social support alongside addiction treatment',
    ],
    snippet: (loc) => `Spice (synthetic cannabinoids) addiction is a serious and growing problem across the UK, particularly among homeless populations and in prison. Spice can cause severe psychosis, collapse, and death. Free help is available in ${loc} through NHS drug services. Call Frank on 0300 123 6600 (free, 24/7) for spice addiction help in ${loc}.`,
    faqs: (loc) => [
      { question: `What is spice and why is it dangerous?`, answer: `Spice is the street name for synthetic cannabinoids — man-made chemicals sprayed onto plant material and smoked. Unlike cannabis, spice is far more potent and unpredictable. It can cause severe psychosis, seizures, cardiac arrest, and death. The chemical composition of spice varies constantly — users never know what they are taking.` },
      { question: `How do I get help for spice addiction in ${loc}?`, answer: `NHS drug services in ${loc} increasingly deal with spice addiction. Self-refer via Frank (0300 123 6600) or speak to your GP. If someone has collapsed or is experiencing psychosis after using spice, call 999 immediately. Spice is often served alongside homelessness and mental health issues — integrated support is available.` },
      { question: `Is spice legal in the UK?`, answer: `No. Spice and all synthetic cannabinoids were banned under the Psychoactive Substances Act 2016. Possession, supply, and production are illegal. Before 2016, spice was sold legally in shops as a "legal high" — this is no longer the case.` },
      { question: `Why is spice so common among homeless people?`, answer: `Spice became widespread in the UK homeless population and in prisons partly because it was initially legal and cheap, and partly because its water solubility makes it harder to detect in drug tests. It has caused widespread health crises in both settings. NHS services and homelessness charities in ${loc} provide specialist support.` },
      { question: `Can spice cause permanent mental health damage?`, answer: `Yes. Heavy long-term spice use can cause persistent psychosis, cognitive impairment, and anxiety disorders that last long after stopping. Early intervention and treatment significantly improve outcomes. Psychiatric assessment as part of addiction treatment in ${loc} is essential.` },
    ],
  },

  'gambling-addiction': {
    slug: 'gambling-addiction',
    name: 'Gambling Addiction',
    nameAdjective: 'gambling',
    type: 'alcohol',
    signs: [
      'Being preoccupied with gambling — constantly thinking about the next bet',
      'Needing to bet increasing amounts to get the same excitement',
      'Repeated failed attempts to cut down or stop gambling',
      'Gambling to escape problems, relieve anxiety, or negative mood',
      'Chasing losses — betting more to try to win back money lost',
      'Lying to family members about the extent of gambling',
      'Taking out loans, selling possessions, or stealing to fund gambling',
      'Jeopardising work, relationships, or education because of gambling',
    ],
    withdrawal: [
      'Intense cravings and preoccupation with gambling',
      'Anxiety and restlessness when unable to gamble',
      'Irritability and mood swings',
      'Depression and low mood',
      'Insomnia',
      'Gambling is a behavioural addiction — there is no physical withdrawal',
    ],
    treatment: [
      'GamCare National Helpline (free): 0808 8020 133 — 24/7',
      'NHS National Problem Gambling Clinic (free referral via GP)',
      'Gamblers Anonymous (GA) meetings — free, 12-step',
      'CBT — most evidence-based treatment for gambling disorder',
      'Self-exclusion from gambling sites (GAMSTOP — free, gamstop.co.uk)',
      'Financial counselling and debt management (StepChange: 0800 138 1111)',
    ],
    snippet: (loc) => `Gambling addiction (Gambling Disorder) is a recognised clinical condition that affects up to 0.5% of the UK population — around 300,000 people. Free help is available in ${loc} through GamCare (0808 8020 133, 24/7), NHS Problem Gambling services, and Gamblers Anonymous meetings. Self-exclusion via GAMSTOP is free and available immediately.`,
    faqs: (loc) => [
      { question: `Where can I get gambling addiction help in ${loc}?`, answer: `Free gambling addiction help in ${loc} is available through: GamCare (0808 8020 133, free, 24/7), the NHS National Problem Gambling Clinic (referral via your GP), Gamblers Anonymous meetings (ga.org.uk), and local NHS IAPT services offering CBT for gambling disorder. You can also self-exclude from all UK gambling sites simultaneously via GAMSTOP (free, gamstop.co.uk).` },
      { question: `Is gambling addiction a real medical condition?`, answer: `Yes. Gambling Disorder is classified in the DSM-5 and ICD-11 as a recognised behavioural addiction. It affects the same dopamine reward pathways as substance addictions. It is not a character failing or lack of willpower — it is a clinical condition that responds well to treatment, particularly CBT.` },
      { question: `How do I block myself from gambling sites?`, answer: `GAMSTOP (gamstop.co.uk) is a free, UK government-backed self-exclusion scheme. Registering creates a block on all UKGC-licensed gambling sites and apps for a minimum of 6 months, 1 year, or 5 years. This is one of the most effective immediate interventions. You can also ask your bank to block gambling transactions.` },
      { question: `What is the link between gambling and debt?`, answer: `Gambling addiction and problem debt are closely linked — the majority of people with a serious gambling problem are in significant debt. StepChange (0800 138 1111, free) provides debt counselling specifically for people whose debt is gambling-related. Treating the gambling addiction and the debt together produces the best outcomes.` },
      { question: `Can gambling addiction be treated on the NHS?`, answer: `Yes. The NHS National Problem Gambling Clinic (based in London with services available nationally) offers specialist treatment for gambling disorder including CBT, individual therapy, and group therapy. Referral is via your GP. NHS IAPT services throughout ${loc} also offer CBT for gambling. Wait times vary.` },
      { question: `I think my partner has a gambling problem — what can I do?`, answer: `GamCare's helpline (0808 8020 133) supports not just the person gambling but also their families. GamAnon (gamanon.org.uk) runs free meetings for family members. Protecting joint finances — separate bank accounts, reviewed direct debits — is often an urgent priority. You cannot force someone to stop, but you can protect yourself and encourage professional help.` },
    ],
  },

  'nitrous-oxide-addiction': {
    slug: 'nitrous-oxide-addiction',
    name: 'Nitrous Oxide',
    nameAdjective: 'nitrous oxide',
    type: 'drug',
    signs: [
      'Using nitrous oxide (laughing gas) multiple times a week or daily',
      'Needing increasing canisters to achieve the same effect',
      'Continuing to use despite tingling or numbness in hands and feet (nerve damage)',
      'Using alone rather than socially',
      'Spending significant money on nitrous oxide canisters',
      'Unable to stop or reduce despite wanting to',
    ],
    withdrawal: [
      'Psychological cravings',
      'Anxiety and low mood',
      'Nitrous oxide does not produce significant physical withdrawal',
      'The main risk is neurological damage from heavy use — not withdrawal',
    ],
    treatment: [
      'NHS drug treatment services (increasingly seeing nitrous oxide users)',
      'Vitamin B12 supplementation — essential if neurological symptoms present',
      'Neurological assessment if numbness, weakness, or walking problems',
      'CBT for psychological dependency',
      'NA meetings',
    ],
    snippet: (loc) => `Nitrous oxide (laughing gas) was made a Class C drug in the UK in November 2023. Heavy use causes severe vitamin B12 deficiency and permanent neurological damage. Help for nitrous oxide dependency is available in ${loc} through NHS drug services — call Frank on 0300 123 6600 (free, 24/7).`,
    faqs: (loc) => [
      { question: `Is nitrous oxide illegal in the UK?`, answer: `Yes. Nitrous oxide became a Class C controlled drug in the UK in November 2023. Possession can result in up to 2 years in prison and an unlimited fine. Supply carries up to 14 years. This change was driven by rising use among young people and associated health harms.` },
      { question: `What are the health risks of nitrous oxide?`, answer: `The primary health risk of heavy nitrous oxide use is severe vitamin B12 deficiency, which causes subacute combined degeneration of the spinal cord — a serious neurological condition causing numbness, weakness, difficulty walking, and in severe cases, paralysis. Symptoms can appear surprisingly quickly with heavy use. If you have tingling or numbness, see a GP immediately.` },
      { question: `Where can I get help for nitrous oxide use in ${loc}?`, answer: `NHS drug services in ${loc} can help with nitrous oxide dependency. Speak to your GP about vitamin B12 levels if you have been using heavily. You can self-refer to drug services via Frank (0300 123 6600). If you have neurological symptoms (tingling, weakness, difficulty walking), attend A&E immediately — this is a medical emergency.` },
    ],
  },
}
